---
- name: copy flume
  unarchive: src=apache-flume-1.5.0-bin.tar.gz dest=/opt
       
- name: create link
  file: src=/opt/apache-flume-1.5.0-bin dest=/opt/flume state=link owner=lukasz

- name: flume temp
  file: dest=/app/flume owner=lukasz state=directory

#- name: flume conf
#  template: src={{ item }} dest=/with/opt/flume
#  conf_items:
#    -

- name: .bashrc
  template: src=.bashrc dest=/home/lukasz
